[package]
name = "runes"
version = "0.0.1"
authors = [ "laudleon@gmail.com" ]

[[bin]]
name = "runes"
path = "src/main.rs"

[dependencies]
mos6502 = { path = "mos6502" }

[dependencies.sdl2]
version = "0.34"
default-features = false
features = ["ttf"]
